name:                my-xmonad
version:             0.1.0.0
github:              "smb374/my-xmonad"
license:             BSD3
author:              "Po-Yeh Chen"
maintainer:          "smb374.cs08@nctu.edu.tw"
copyright:           "2022 Po-Yeh Chen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smb374/my-xmonad#readme>

dependencies:
  - base >= 4.7 && < 5
  - xmonad >= 0.17
  - xmonad-contrib >= 0.17

library:
  source-dirs: src

executables:
  my-xmonad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad

tests:
  my-xmonad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - my-xmonad
