name:                my-xmonad
version:             0.1.0.0
github:              "smb374/my-xmonad"
license:             BSD3
author:              "Po-Yeh Chen"
maintainer:          "smb374.cs08@nctu.edu.tw"
copyright:           "2022 Po-Yeh Chen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/smb374/my-xmonad#readme>

dependencies:
  - base >= 4.7 && < 5
  - xmonad >= 0.17
  - xmonad-contrib >= 0.17
  - X11 >= 1.10
  - containers
  - text

# library:
#   source-dirs: src

executables:
  xmonad:
    main:                xmonad.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # dependencies:
    # - my-xmonad

